insert into iam.permissions (id, code, name) values
  (gen_random_uuid(), 'auth.login', 'Realizar login'),
  (gen_random_uuid(), 'user.read', 'Consultar usuários'),
  (gen_random_uuid(), 'user.create', 'Criar usuários'),
  (gen_random_uuid(), 'user.update', 'Atualizar usuários'),
  (gen_random_uuid(), 'user.manage_roles', 'Gerir papéis de usuários'),
  (gen_random_uuid(), 'user.manage_scopes', 'Gerir escopos de usuários'),
  (gen_random_uuid(), 'organization.read', 'Consultar organizações'),
  (gen_random_uuid(), 'organization.create', 'Criar organizações'),
  (gen_random_uuid(), 'organization.update', 'Atualizar organizações'),
  (gen_random_uuid(), 'vereador.read', 'Consultar vereadores'),
  (gen_random_uuid(), 'vereador.create', 'Criar vereadores'),
  (gen_random_uuid(), 'vereador.update', 'Atualizar vereadores'),
  (gen_random_uuid(), 'team.read', 'Consultar equipes'),
  (gen_random_uuid(), 'team.create', 'Criar equipes'),
  (gen_random_uuid(), 'team.update', 'Atualizar equipes'),
  (gen_random_uuid(), 'person.read', 'Consultar pessoas'),
  (gen_random_uuid(), 'person.create', 'Criar pessoas'),
  (gen_random_uuid(), 'person.update', 'Atualizar pessoas'),
  (gen_random_uuid(), 'person.link', 'Vincular pessoa a contexto'),
  (gen_random_uuid(), 'consent.read', 'Consultar consentimentos'),
  (gen_random_uuid(), 'consent.create', 'Criar consentimentos'),
  (gen_random_uuid(), 'consent.revoke', 'Revogar consentimentos'),
  (gen_random_uuid(), 'capture.read', 'Consultar captações'),
  (gen_random_uuid(), 'capture.create', 'Criar captações'),
  (gen_random_uuid(), 'capture.classify', 'Classificar captações'),
  (gen_random_uuid(), 'capture.forward', 'Encaminhar captações'),
  (gen_random_uuid(), 'capture.convert', 'Converter captação em beneficiário'),
  (gen_random_uuid(), 'polo.read', 'Consultar polos'),
  (gen_random_uuid(), 'polo.create', 'Criar polos'),
  (gen_random_uuid(), 'polo.update', 'Atualizar polos'),
  (gen_random_uuid(), 'polo.manage_beneficiary', 'Gerir beneficiários do polo'),
  (gen_random_uuid(), 'modality.read', 'Consultar modalidades'),
  (gen_random_uuid(), 'modality.create', 'Criar modalidades'),
  (gen_random_uuid(), 'modality.update', 'Atualizar modalidades'),
  (gen_random_uuid(), 'attendance.read', 'Consultar frequências'),
  (gen_random_uuid(), 'attendance.create', 'Registrar frequências'),
  (gen_random_uuid(), 'occurrence.read', 'Consultar ocorrências'),
  (gen_random_uuid(), 'occurrence.create', 'Registrar ocorrências'),
  (gen_random_uuid(), 'daily_log.read', 'Consultar diário do polo'),
  (gen_random_uuid(), 'daily_log.create', 'Criar diário do polo'),
  (gen_random_uuid(), 'purchase_request.read', 'Consultar pedidos de compra'),
  (gen_random_uuid(), 'purchase_request.create', 'Criar pedidos de compra'),
  (gen_random_uuid(), 'cabinet.read', 'Consultar gabinete'),
  (gen_random_uuid(), 'cabinet.action.read', 'Consultar ações do gabinete'),
  (gen_random_uuid(), 'cabinet.action.create', 'Criar ações do gabinete'),
  (gen_random_uuid(), 'task.read', 'Consultar tarefas'),
  (gen_random_uuid(), 'task.create', 'Criar tarefas'),
  (gen_random_uuid(), 'task.update', 'Atualizar tarefas'),
  (gen_random_uuid(), 'task.complete', 'Concluir tarefas'),
  (gen_random_uuid(), 'demand.read', 'Consultar demandas'),
  (gen_random_uuid(), 'demand.create', 'Criar demandas'),
  (gen_random_uuid(), 'demand.update', 'Atualizar demandas'),
  (gen_random_uuid(), 'demand.assign', 'Atribuir demandas'),
  (gen_random_uuid(), 'event.read', 'Consultar eventos e atividades'),
  (gen_random_uuid(), 'event.create', 'Criar eventos e atividades'),
  (gen_random_uuid(), 'event.update', 'Atualizar eventos e atividades'),
  (gen_random_uuid(), 'dashboard.admin.read', 'Consultar dashboard administrativo'),
  (gen_random_uuid(), 'dashboard.vereador.read', 'Consultar dashboard do vereador'),
  (gen_random_uuid(), 'dashboard.polo.read', 'Consultar dashboard do polo'),
  (gen_random_uuid(), 'dashboard.cabinet.read', 'Consultar dashboard do gabinete'),
  (gen_random_uuid(), 'geo.read', 'Consultar camadas geográficas'),
  (gen_random_uuid(), 'geo.manage', 'Gerir camadas geográficas'),
  (gen_random_uuid(), 'report.read', 'Consultar relatórios'),
  (gen_random_uuid(), 'report.export', 'Exportar relatórios'),
  (gen_random_uuid(), 'audit.read', 'Consultar auditoria'),
  (gen_random_uuid(), 'privacy.read', 'Consultar solicitações de privacidade'),
  (gen_random_uuid(), 'privacy.process', 'Processar solicitações de privacidade')
on conflict (code) do nothing;
